language: python

python:
  - "3.7"

sudo: false

install:
  - pip install -e .
  - geohc create-instance

script:
  - geohc db-create
  - geohc db-adduser -u admin -p test -e you@example.com -r admin
  - flake8
  - geohc db-load -y tests/data/fixtures.json -y
  - geohc run-healthchecks
  - geohc run-tests
  - cd docs && make html

after-script:
  - geohc db-drop
